### ISSUE TITLE
It's time to stop releasing reauthored works

### ISSUE THREAD

**Issue by AntaresOne** [g7755725/GamerROM-8#1]
Hi,
I'm AntaresOne, the lead developer of "Optimized CyanogenMod 12.1" ROM by the JDCTeam.
You have been warned more than once since early June to stop releasing your ROMs based on the JDCTeam Optimized CyanogenMod 12.1 builds (already built, zipped and released!!!) as you are just adding useless build.prop entries, Google apps, your own settings for the OTA updates and reauthoring something made by others (us) as your own work all across the net like on XDA forum, YouTube, your forum at http://cyberdevdevelopment.boards.net and your Rapcity Entertainnment Network Facebook page.

At today, 2 July, you are still releasing your ROMs using our update, already built and zipped, as base. This is kinda unacceptable and disrespectful.

Please delete everything you released based on our work as I'm going to not forgive you anymore.

Why don't you compile yourself? All the source code and guidelines are in our git at https://github.com/JDCTeam, what we ask is to make consistent modifications because having the same ROM released for the same platform is useless.

This is not the right way to make experience. Try starting from the official CyanogenMod git at https://github.com/CyanogenMod and their wiki page at http://wiki.cyanogenmod.org

**Comment by g7755725** [comment]
This isnt a issue and we are complying as GamerROM 8 doesnt use your work please do not use issue tracking as a none issue with gamer rom 8, gamerrom 5 will be deleted as folliws due to gamerrom 8 so im closing this an clarifying as a complaint and solved

**Comment by AntaresOne** [comment]
Man, seriously, are you kidding me?
In the https://romhut.com/versions/gr8_v1-3_for_jfltetmo-zip ROM there is blockimage update. Then there are some files that are not written inside system folder.

From build.prop inside system folder:
ro.build.version.incremental=21AFC7E54 <- this is UNIQUE for each ROM build, why I have the same code inside my Optimized CM12.1 2 June build?

ro.build.date.utc=1433254086 <- same as above, UNIQUE, I have this exact code in my 2 June build. Convert it on http://www.epochconverter.com, will tell you "Tue, 02 Jun 2015 14:08:06 GMT"

wget binary, why you have it inside your folder while it's ONLY in my ROM?

loki.sh inside system/etc folder:
"# Update for MultiROM by Mattia "AntaresOne" D'Alleva" why do you have this if you use a blockimage specifically for the T-Mobile variant and it is ONLY in my ROM?

Oh, there's also @Alucard24's kernel, he didn't give you permission to integrate it in your ROM.

**Comment by g7755725** [comment]
Dude just because wget is in their doesnt mean its from your rom and 2nd of all none if this build is from yours if you have a problem with my development then thats fine, but he released it to tge public and its just for stweaks app. dude do u have a life other then taking 10 mins out of your life to say that, really am i really worth your time to even argue, just because you hate me or dont agree of what i do, and if you dont like it why are you downloadong and installing my rom if you hate me why not go somewhere else and leave my stuff alone instead of using my stuff, no one is forcing you and complaining about my work isnt helping and 3rd of all just because im using a third party kernel doesnt mean its from yours, their are thousands of kernels out there, and apperantly you do not understand a true meaning of open source just because i dont follow full src or gpl doesnt mean im breaking a law if there was i would be in jail right now and as well i dont need to release a src because if any other company dont want to  doesnt mean i have to open source is something u build on your free time im not getting paid for it, im just love doing it to kill time so please walk away it aint worth it..
